# Generated by scripts/update-dist-manifests.py for Wright 0.3.0.
# Consumes the canonical macOS release archives; do not edit by hand.
class Wright < Formula
  desc "Tooling-first semantic platform for the Overwatch Workshop and OverPy ecosystem"
  homepage "https://github.com/wrightkit/wright"
  url "https://github.com/wrightkit/wright/releases/download/v0.3.0/wright-0.3.0-aarch64-apple-darwin.tar.gz"
  sha256 "577dc916eaef350bf600a34964a68cd03801cd7794dabb8c9bdd2d6ff12a2a1c"
  license "AGPL-3.0-or-later"

  resource "wright-intel" do
    on_intel do
      url "https://github.com/wrightkit/wright/releases/download/v0.3.0/wright-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "9d91f8d3853f69943a52fe5f3aa40768d4a234cb118be7d4987ae554621a6f36"
    end
  end

  def install
    if Hardware::CPU.intel?
      resource("wright-intel").stage do
        bin.install "wright"
        bin.install "wright-lsp"
      end
    else
      bin.install "wright"
      bin.install "wright-lsp"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wright --version")
    assert_match version.to_s, shell_output("#{bin}/wright-lsp --version")
  end
end
