# Generated by scripts/update-dist-manifests.py for Wright 0.2.30.
# Consumes the canonical macOS release archives; do not edit by hand.
class Wright < Formula
  desc "Tooling-first semantic platform for the Overwatch Workshop and OverPy ecosystem"
  homepage "https://github.com/wrightkit/wright"
  url "https://github.com/wrightkit/wright/releases/download/v0.2.30/wright-0.2.30-aarch64-apple-darwin.tar.gz"
  sha256 "7fbab818d576e84247bd35d0ef1aa8a0390e4ee1b30574c4686c6e23a5d38944"
  license "AGPL-3.0-or-later"

  resource "wright-intel" do
    on_intel do
      url "https://github.com/wrightkit/wright/releases/download/v0.2.30/wright-0.2.30-x86_64-apple-darwin.tar.gz"
      sha256 "9690229c10919ebf2cab86c370799acbacae69754134c49b6436967a15a0ae1a"
    end
  end

  def install
    if Hardware::CPU.intel?
      resource("wright-intel").stage do
        bin.install "wright"
        bin.install "wright-lsp"
      end
    else
      bin.install "wright"
      bin.install "wright-lsp"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wright --version")
    assert_match version.to_s, shell_output("#{bin}/wright-lsp --version")
  end
end
