# Generated by scripts/update-dist-manifests.py for Wright 0.2.9.
# Consumes the canonical macOS release archives; do not edit by hand.
class Wright < Formula
  desc "Tooling-first semantic platform for the Overwatch Workshop and OverPy ecosystem"
  homepage "https://github.com/wrightkit/wright"
  url "https://github.com/wrightkit/wright/releases/download/v0.2.9/wright-0.2.9-aarch64-apple-darwin.tar.gz"
  sha256 "8ceb1c4669dbeb4f6ad7033951e2dbc9a8e1fe8781ccdbed5b31da9c5475b462"
  license "AGPL-3.0-or-later"

  resource "wright-intel" do
    on_intel do
      url "https://github.com/wrightkit/wright/releases/download/v0.2.9/wright-0.2.9-x86_64-apple-darwin.tar.gz"
      sha256 "848f064989797f0bc28e6709a164bee2c02b51e74ac6fa068e461f6c080812b4"
    end
  end

  def install
    if Hardware::CPU.intel?
      resource("wright-intel").stage do
        bin.install "wright"
        bin.install "wright-lsp"
      end
    else
      bin.install "wright"
      bin.install "wright-lsp"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wright --version")
    assert_match version.to_s, shell_output("#{bin}/wright-lsp --version")
  end
end
